resolver: lts-22.30

nix:
  pure: false
  packages:
  - zlib

packages:
# - ./v1.36
# - ./v1.37
# - ./v1.38
# - ./v1.39
# - ./v1.40
# - ./v1.41
# - ./v1.42
# - ./v1.43
- ./v1.44

- ./integration-tests
