{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import DockerEngine.Model
import DockerEngine.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy AuthConfig)
      propMimeEq MimeJSON (Proxy :: Proxy BuildInfo)
      propMimeEq MimeJSON (Proxy :: Proxy ClusterInfo)
      propMimeEq MimeJSON (Proxy :: Proxy Config)
      propMimeEq MimeJSON (Proxy :: Proxy ConfigSpec)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerConfigVolumes)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerSummary)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerSummaryHostConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerSummaryNetworkSettings)
      propMimeEq MimeJSON (Proxy :: Proxy CreateImageInfo)
      propMimeEq MimeJSON (Proxy :: Proxy DeviceMapping)
      propMimeEq MimeJSON (Proxy :: Proxy EndpointPortConfig)
      propMimeEq MimeJSON (Proxy :: Proxy EndpointSettings)
      propMimeEq MimeJSON (Proxy :: Proxy EndpointSettingsIPAMConfig)
      propMimeEq MimeJSON (Proxy :: Proxy EndpointSpec)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorDetail)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorResponse)
      propMimeEq MimeJSON (Proxy :: Proxy GraphDriverData)
      propMimeEq MimeJSON (Proxy :: Proxy HealthConfig)
      propMimeEq MimeJSON (Proxy :: Proxy HostConfig)
      propMimeEq MimeJSON (Proxy :: Proxy HostConfigAllOf)
      propMimeEq MimeJSON (Proxy :: Proxy HostConfigAllOfLogConfig)
      propMimeEq MimeJSON (Proxy :: Proxy HostConfigAllOfPortBindings)
      propMimeEq MimeJSON (Proxy :: Proxy IPAM)
      propMimeEq MimeJSON (Proxy :: Proxy IdResponse)
      propMimeEq MimeJSON (Proxy :: Proxy Image)
      propMimeEq MimeJSON (Proxy :: Proxy ImageDeleteResponseItem)
      propMimeEq MimeJSON (Proxy :: Proxy ImageRootFS)
      propMimeEq MimeJSON (Proxy :: Proxy ImageSummary)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject1)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject2)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject3)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject4)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject5)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject6)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject7)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject8)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse200)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2001)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20011)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20011Actor)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20012)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20013)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20014)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20015)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20016)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20017)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20018)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20018JoinTokens)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20019)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2002)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20020)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20020Descriptor)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20020Platforms)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2004)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2005)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2006)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2007)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2008)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2009)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2009Plugins)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2009RegistryConfig)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2009RegistryConfigIndexConfigs)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse201)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2011)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2012)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2013)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2014)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse400)
      propMimeEq MimeJSON (Proxy :: Proxy InspectResponse)
      propMimeEq MimeJSON (Proxy :: Proxy InspectResponseState)
      propMimeEq MimeJSON (Proxy :: Proxy Mount)
      propMimeEq MimeJSON (Proxy :: Proxy MountBindOptions)
      propMimeEq MimeJSON (Proxy :: Proxy MountPoint)
      propMimeEq MimeJSON (Proxy :: Proxy MountTmpfsOptions)
      propMimeEq MimeJSON (Proxy :: Proxy MountVolumeOptions)
      propMimeEq MimeJSON (Proxy :: Proxy MountVolumeOptionsDriverConfig)
      propMimeEq MimeJSON (Proxy :: Proxy Network)
      propMimeEq MimeJSON (Proxy :: Proxy NetworkConfig)
      propMimeEq MimeJSON (Proxy :: Proxy NetworkContainer)
      propMimeEq MimeJSON (Proxy :: Proxy Node)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescription)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescriptionEngine)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescriptionEnginePlugins)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescriptionPlatform)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescriptionResources)
      propMimeEq MimeJSON (Proxy :: Proxy NodeSpec)
      propMimeEq MimeJSON (Proxy :: Proxy ObjectVersion)
      propMimeEq MimeJSON (Proxy :: Proxy Plugin)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfig)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigArgs)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigInterface)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigLinux)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigNetwork)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigRootfs)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigUser)
      propMimeEq MimeJSON (Proxy :: Proxy PluginDevice)
      propMimeEq MimeJSON (Proxy :: Proxy PluginEnv)
      propMimeEq MimeJSON (Proxy :: Proxy PluginInterfaceType)
      propMimeEq MimeJSON (Proxy :: Proxy PluginMount)
      propMimeEq MimeJSON (Proxy :: Proxy PluginSettings)
      propMimeEq MimeJSON (Proxy :: Proxy Port)
      propMimeEq MimeJSON (Proxy :: Proxy ProcessConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ProgressDetail)
      propMimeEq MimeJSON (Proxy :: Proxy PushImageInfo)
      propMimeEq MimeJSON (Proxy :: Proxy Resources)
      propMimeEq MimeJSON (Proxy :: Proxy ResourcesBlkioWeightDevice)
      propMimeEq MimeJSON (Proxy :: Proxy ResourcesUlimits)
      propMimeEq MimeJSON (Proxy :: Proxy RestartPolicy)
      propMimeEq MimeJSON (Proxy :: Proxy Secret)
      propMimeEq MimeJSON (Proxy :: Proxy SecretSpec)
      propMimeEq MimeJSON (Proxy :: Proxy Service)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceEndpoint)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceEndpointVirtualIPs)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpec)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpecMode)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpecModeReplicated)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpecRollbackConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpecUpdateConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceUpdateResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceUpdateStatus)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpec)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecCAConfig)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecCAConfigExternalCAs)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecDispatcher)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecEncryptionConfig)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecOrchestration)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecRaft)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecTaskDefaults)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecTaskDefaultsLogDriver)
      propMimeEq MimeJSON (Proxy :: Proxy TLSInfo)
      propMimeEq MimeJSON (Proxy :: Proxy Task)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpec)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpec)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpecConfigs)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpecDNSConfig)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpecFile)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpecPrivileges)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpecPrivilegesCredentialSpec)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpecPrivilegesSELinuxContext)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpecSecrets)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecLogDriver)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecNetworks)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecPlacement)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecPlacementPreferences)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecPlacementSpread)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecResources)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecResourcesLimits)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecResourcesReservation)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecRestartPolicy)
      propMimeEq MimeJSON (Proxy :: Proxy TaskState)
      propMimeEq MimeJSON (Proxy :: Proxy TaskStatus)
      propMimeEq MimeJSON (Proxy :: Proxy TaskStatusContainerStatus)
      propMimeEq MimeJSON (Proxy :: Proxy ThrottleDevice)
      propMimeEq MimeJSON (Proxy :: Proxy Volume)
      propMimeEq MimeJSON (Proxy :: Proxy VolumeUsageData)
      
