name:                docker-engine-integration-tests
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- sandwich

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: lib
  dependencies:
  - aeson
  - bytestring
  - containers
  - docker-engine
  - exceptions
  - hostname
  - http-client
  - http-types
  - iproute
  - monad-control
  - monad-logger
  - network
  - random
  - relude
  - retry
  - safe
  - string-interpolate
  - text
  - unliftio
  - unliftio-core

executables:
  docker-engine-integration-tests:
    main: Main.hs
    source-dirs: app
