name: ci

on:
  pull_request:
  push:

jobs:
  # cabal:
  #   name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macOS-latest, windows-latest]
  #       ghc:
  #       - "8.6.5"
  #       - "8.8.4"
  #       - "8.10.7"
  #       - "9.0.2"
  #       - "9.2.7"
  #       - "9.4.5"
  #       - "9.6.2"

  #   steps:
  #   - uses: actions/checkout@v3

  #   - uses: haskell-actions/setup@v2
  #     id: setup-haskell-cabal
  #     name: Setup Haskell
  #     with:
  #       ghc-version: ${{ matrix.ghc }}
  #       cabal-version: "latest"

  #   - name: Freeze
  #     run: |
  #       cabal freeze

  #   - uses: actions/cache@v4
  #     name: Cache ~/.cabal/store
  #     with:
  #       path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
  #       key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

  #   - name: Build
  #     run: |
  #       cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
  #       cabal build all

  #   - name: Test
  #     run: |
  #       cabal test all

  stack:
    name: stack ${{matrix.resolver}} / API ${{ matrix.version.api_version }} / Docker ${{ matrix.version.docker_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        resolver:
        - nightly-2024-07-26 # 9.8.2
        - lts-22.30 # 9.6.6
        - lts-21.25 # 9.4.8
        - lts-20.26 # 9.2.8
        - lts-19.33 # 9.0.2
        - lts-18.28 # 8.10.7
        version:
        - api_version: v1.46
          docker_version: 27.1
        - api_version: v1.45
          docker_version: 26.1
        - api_version: v1.44
          docker_version: 25.0
        - api_version: v1.43
          docker_version: 24.0
        - api_version: v1.42
          docker_version: 23.0
        - api_version: v1.41
          docker_version: 20.10
        # - api_version: v1.40
        #   docker_version: 19.03
        # - api_version: v1.39
        #   docker_version: 18.09
        # - api_version: v1.38
        #   docker_version: 18.06
        # - api_version: v1.37
        #   docker_version: 18.05
        # - api_version: v1.36
        #   docker_version: 18.02
    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      name: Setup Haskell Stack
      with:
        enable-stack: true
        stack-version: "latest"

    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: ${{ matrix.version.docker_version }}

    - uses: actions/cache@v4
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.version.api_version }}-${{ matrix.resolver }}-stack

    # - name: apt
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y libx11-dev libxext-dev libxinerama-dev libxrandr-dev libxss-dev

    - name: Construct stack.yaml
      run: |
        rm stack.yaml stack.yaml.lock

        cat >stack.yaml <<EOL
        resolver: ${{matrix.resolver}}
        packages:
        - ${{matrix.version.api_version}}
        - ./integration-tests
        EOL

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc

    - name: Integration tests
      run: |
        stack run integration-tests --system-ghc
